---
- hosts: all
  vars:
    aws_region: "{{ aws_region }}"
  become: yes
  tasks:
  - name: Get distro codename
    shell: lsb_release -cs
    register: distro
  - name: Import repo signing keys
    apt_key:
      url: "{{ item }}"
      state: present
    loop:
      - https://nginx.org/keys/nginx_signing.key
      - https://repos.influxdata.com/influxdb.key
      - https://packages.grafana.com/gpg.key
  - name: Add repositories to apt
    apt_repository:
      repo: "{{ item }}"
      state: present
      update_cache: no
    loop:
      - "deb [arch=amd64] http://nginx.org/packages/ubuntu {{ distro.stdout }} nginx"
      - "ppa:costamagnagianfranco/borgbackup"
      - "ppa:certbot/certbot"
      - "deb https://repos.influxdata.com/ubuntu/ {{ distro.stdout }} stable"
      - "deb https://packages.grafana.com/oss/deb stable main"
      - "deb http://archive.ubuntu.com/ubuntu/ {{ distro.stdout }} universe"
      - "deb http://archive.ubuntu.com/ubuntu/ {{ distro.stdout }}-updates universe"
      - "deb http://security.ubuntu.com/ubuntu/ {{ distro.stdout }}-security universe"
  - name: Upgrade all packages to the latest version
    apt:
      update_cache: yes
      upgrade: dist
  - name: Install packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - curl
      - gnupg2
      - ca-certificates
      - lsb-release
      - libgc1c2
      - libyaml-dev
      - nginx
      - git
      - wget
      - jq
      - haveged
      - python-setuptools
      - python-pip
      - borgbackup
      - pwgen
      - nvme-cli
      - influxdb
      - telegraf
      - grafana
      - tmux
      - mc
      - certbot
      - python-certbot-nginx
  - name: Install Amazon EBS tools
    copy:
      src: "{{ item }}"
      dest: /sbin/
      owner: root
      mode: 0755
    with_fileglob:
      - files/sbin/*
  - name: Install udev rule for EBS volumes
    copy:
      src: files/etc/udev/rules.d/70-ec2-nvme-devices.rules
      dest: /etc/udev/rules.d/70-ec2-nvme-devices.rules
      owner: root
      mode: 0644
  - name: Deploy new nginx configuration
    copy:
      src: files/etc/nginx/nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: 0644
  - name: Delete default nginx site configs
    shell: rm /etc/nginx/conf.d/*
  - name: Install nginx default site config
    copy:
      src: files/etc/nginx/conf.d/zzz_default.conf
      dest: /etc/nginx/conf.d/zzz_default.conf
      owner: root
      group: root
      mode: 0644
  - name: Enable haveged service
    systemd:
      name: haveged
      enabled: yes
      state: started
  - name: Create directory for cfn-init
    file:
      path: /opt/aws/bin
      state: directory
  - name: Create directory for cfn configs
    file:
      path: /etc/cfn/hooks.d
      state: directory
  - name: Install cfn-init
    shell: python /usr/lib/python2.7/dist-packages/easy_install.py --script-dir /opt/aws/bin https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
  - name: Create mountpoint for data disk
    file:
      path: /data
      state: directory
  - name: Install modified fstab
    copy:
      src: files/etc/fstab
      dest: /etc/fstab
      owner: root
      group: root
      mode: 0644
  - name: Install sysctl configs
    copy:
      src: "{{ item }}"
      dest: /etc/sysctl.d/
      owner: root
      mode: 0644
    with_fileglob:
      - files/etc/sysctl.d/*
  - name: Copy awslogs agent base configuration
    copy:
      src: files/awslogs.conf
      dest: /tmp/awslogs.conf
      owner: root
      group: root
      mode: 0644
  - name: Download awslogs agent
    get_url:
      url: "https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py"
      dest: "/tmp/awslogs-agent-setup.py"
      mode: 0755
      force: yes
  - name: Install awslogs agent
    shell: "python /tmp/awslogs-agent-setup.py --region {{ aws_region }} --non-interactive -c /tmp/awslogs.conf"
  - name: Disable grafana and influxdb services
    systemd:
      name: "{{ item }}"
      enabled: no
      state: stopped
    loop:
      - influxdb
      - telegraf
      - grafana-server
